### ISSUE TITLE
Visual enhancement suggestion

### ISSUE THREAD

**Issue by alexkiri** [akouzoukos/apotris#1]
Here a nice visual effect that looks really nice. I am referring to the colored outline of each piece that appears when you drop it. 

![video](https://user-images.githubusercontent.com/6061770/189472418-12fea04a-84a5-4976-8eb6-831a441ffd42.mp4)
Credit goes to u/SpilledCobra872
https://www.reddit.com/r/Tetris/comments/wk33x8/i_made_a_little_pixel_animation/

Also, do you take pull requests? I've never programmed a GBA homebrew, but I really appreciate that the game is open source. I would gladly help improving it.

**Comment by akouzoukos** [comment]
Damn, that looks really nice! I'm definitely adding that!

I'm certainly open to pull requests!

**Comment by akouzoukos** [comment]
I couldn't wait to see how this would look in Apotris, so I already added it :P

![demo](https://user-images.githubusercontent.com/46427677/189488415-bea33679-6081-40eb-95b3-7af9be5b224a.gif)

I even made it spin when the last move was a rotation, though during t-spins you can't really see it because it's behind blocks

![demo2](https://user-images.githubusercontent.com/46427677/189488394-0aaf23f9-a5fb-4cf4-9260-0bfcd9029cd6.gif)

**Comment by Sqwrrly** [comment]
That looks awesome!

**Comment by alexkiri** [comment]
that was fast! and it looks absolutely fantastic!! well done
