### ISSUE TITLE
Enable Select button to be mapped

### ISSUE THREAD

**Issue by Dr-KerbalMD** [akouzoukos/apotris#2]
Rosy Retrospection puts Hold on Select which I find to be very convenient! Unfortunately, I can't seem to map select in the Apotris settings. Using a Miyoo Mini if that matters, but Select works in other games so I know it is mapped correctly.

I would love to be able to map the Select button in Apotris!

**Comment by akouzoukos** [comment]
Yeah I'm planning on adding that!
Not being able to bind Select was intentional, since it's used as a menu button in Training. I couldn't think of a simple way fixing this, and I didn't want to delay the update even more so I decided to leave it for later.

In the meantime, try using A + B to hold! I found it quite comfortable on my Miyoo Mini. Or if you're comfortable with tweaking Retroarch settings, you can also rebind the X or Y buttons to press L/R instead of the default Turbo A/B! I do this myself but for 180 spins.

**Comment by akouzoukos** [comment]
Added this in v3.2.0!
